// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QueryConfig, ResponseBody } from 'redux-query'
import * as runtime from '../runtime'
import {
  AppointmentTagSerializerRead,
  AppointmentTagSerializerReadFromJSON,
} from '../models'

export interface AppointmentTagsGetAppointmentTagByIdRequest {
  id: number
}

/**
 * Return an appointment tags by his id
 */
function appointmentTagsGetAppointmentTagByIdRaw<T>(
  requestParameters: AppointmentTagsGetAppointmentTagByIdRequest,
  requestConfig: runtime.TypedQueryConfig<T, AppointmentTagSerializerRead> = {},
): QueryConfig<T> {
  if (requestParameters.id === null || requestParameters.id === undefined) {
    throw new runtime.RequiredError(
      'id',
      'Required parameter requestParameters.id was null or undefined when calling appointmentTagsGetAppointmentTagById.',
    )
  }

  let queryParameters = null

  const headerParameters: runtime.HttpHeaders = {}

  const { meta = {} } = requestConfig

  meta.authType = ['bearer']
  const config: QueryConfig<T> = {
    url: `${runtime.Configuration.basePath}/appointment_tags/{id}`.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters.id)),
    ),
    meta,
    update: requestConfig.update,
    queryKey: requestConfig.queryKey,
    optimisticUpdate: requestConfig.optimisticUpdate,
    force: requestConfig.force,
    rollback: requestConfig.rollback,
    options: {
      method: 'GET',
      headers: headerParameters,
    },
    body: queryParameters,
  }

  const { transform: requestTransform } = requestConfig
  if (requestTransform) {
    config.transform = (body: ResponseBody, text: ResponseBody) =>
      requestTransform(AppointmentTagSerializerReadFromJSON(body), text)
  }

  return config
}

/**
 * Return an appointment tags by his id
 */
export function appointmentTagsGetAppointmentTagById<T>(
  requestParameters: AppointmentTagsGetAppointmentTagByIdRequest,
  requestConfig?: runtime.TypedQueryConfig<T, AppointmentTagSerializerRead>,
): QueryConfig<T> {
  return appointmentTagsGetAppointmentTagByIdRaw(
    requestParameters,
    requestConfig,
  )
}

/**
 * Return a list of appointments tags
 */
function appointmentTagsGetAppointmentTagsRaw<T>(
  requestConfig: runtime.TypedQueryConfig<
    T,
    Array<AppointmentTagSerializerRead>
  > = {},
): QueryConfig<T> {
  let queryParameters = null

  const headerParameters: runtime.HttpHeaders = {}

  const { meta = {} } = requestConfig

  meta.authType = ['bearer']
  const config: QueryConfig<T> = {
    url: `${runtime.Configuration.basePath}/appointment_tags`,
    meta,
    update: requestConfig.update,
    queryKey: requestConfig.queryKey,
    optimisticUpdate: requestConfig.optimisticUpdate,
    force: requestConfig.force,
    rollback: requestConfig.rollback,
    options: {
      method: 'GET',
      headers: headerParameters,
    },
    body: queryParameters,
  }

  const { transform: requestTransform } = requestConfig
  if (requestTransform) {
    config.transform = (body: ResponseBody, text: ResponseBody) =>
      requestTransform(body.map(AppointmentTagSerializerReadFromJSON), text)
  }

  return config
}

/**
 * Return a list of appointments tags
 */
export function appointmentTagsGetAppointmentTags<T>(
  requestConfig?: runtime.TypedQueryConfig<
    T,
    Array<AppointmentTagSerializerRead>
  >,
): QueryConfig<T> {
  return appointmentTagsGetAppointmentTagsRaw(requestConfig)
}
