#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if npm run format; then
  echo "Code formatted successfully 👍"
else
  echo "Code formatting failed 😢"
  exit 1
fi

if npm run lint; then
  echo "Linting passed 👍"
else
  echo "Linting failed 😢"
  exit 1
fi