// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgencySerializerPost
 */
export interface AgencySerializerPost  {
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerPost
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerPost
     */
    fee_id?: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerPost
     */
    address_id?: number;
}

export function AgencySerializerPostFromJSON(json: any): AgencySerializerPost {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'fee_id': !exists(json, 'fee_id') ? undefined : json['fee_id'],
        'address_id': !exists(json, 'address_id') ? undefined : json['address_id'],
    };
}

export function AgencySerializerPostToJSON(value?: AgencySerializerPost): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'fee_id': value.fee_id,
        'address_id': value.address_id,
    };
}


