// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppointmentSerializerPut
 */
export interface AppointmentSerializerPut  {
    /**
     * 
     * @type {number}
     * @memberof AppointmentSerializerPut
     */
    tag_id?: number;
    /**
     * 
     * @type {string}
     * @memberof AppointmentSerializerPut
     */
    date_start?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentSerializerPut
     */
    date_end?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentSerializerPut
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentSerializerPut
     */
    reminder?: string;
    /**
     * 
     * @type {number}
     * @memberof AppointmentSerializerPut
     */
    property_id?: number;
    /**
     * 
     * @type {number}
     * @memberof AppointmentSerializerPut
     */
    user_id_1?: number;
    /**
     * 
     * @type {number}
     * @memberof AppointmentSerializerPut
     */
    user_id_2?: number;
}

export function AppointmentSerializerPutFromJSON(json: any): AppointmentSerializerPut {
    return {
        'tag_id': !exists(json, 'tag_id') ? undefined : json['tag_id'],
        'date_start': !exists(json, 'date_start') ? undefined : json['date_start'],
        'date_end': !exists(json, 'date_end') ? undefined : json['date_end'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'reminder': !exists(json, 'reminder') ? undefined : json['reminder'],
        'property_id': !exists(json, 'property_id') ? undefined : json['property_id'],
        'user_id_1': !exists(json, 'user_id_1') ? undefined : json['user_id_1'],
        'user_id_2': !exists(json, 'user_id_2') ? undefined : json['user_id_2'],
    };
}

export function AppointmentSerializerPutToJSON(value?: AppointmentSerializerPut): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'tag_id': value.tag_id,
        'date_start': value.date_start,
        'date_end': value.date_end,
        'note': value.note,
        'reminder': value.reminder,
        'property_id': value.property_id,
        'user_id_1': value.user_id_1,
        'user_id_2': value.user_id_2,
    };
}


