// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AppointmentSerializerRead
 */
export interface AppointmentSerializerRead {
  /**
   *
   * @type {number}
   * @memberof AppointmentSerializerRead
   */
  appointmentId?: number
  /**
   *
   * @type {number}
   * @memberof AppointmentSerializerRead
   */
  tagId?: number
  /**
   *
   * @type {string}
   * @memberof AppointmentSerializerRead
   */
  dateStart?: string
  /**
   *
   * @type {string}
   * @memberof AppointmentSerializerRead
   */
  dateEnd?: string
  /**
   *
   * @type {string}
   * @memberof AppointmentSerializerRead
   */
  note?: string
  /**
   *
   * @type {string}
   * @memberof AppointmentSerializerRead
   */
  reminder?: string
  /**
   *
   * @type {number}
   * @memberof AppointmentSerializerRead
   */
  propertyId?: number
  /**
   *
   * @type {number}
   * @memberof AppointmentSerializerRead
   */
  userId1?: number
  /**
   *
   * @type {number}
   * @memberof AppointmentSerializerRead
   */
  userId2?: number
}

export function AppointmentSerializerReadFromJSON(
  json: any,
): AppointmentSerializerRead {
  return {
    appointmentId: !exists(json, 'appointment_id')
      ? undefined
      : json['appointment_id'],
    tagId: !exists(json, 'tag_id') ? undefined : json['tag_id'],
    dateStart: !exists(json, 'date_start') ? undefined : json['date_start'],
    dateEnd: !exists(json, 'date_end') ? undefined : json['date_end'],
    note: !exists(json, 'note') ? undefined : json['note'],
    reminder: !exists(json, 'reminder') ? undefined : json['reminder'],
    propertyId: !exists(json, 'property_id') ? undefined : json['property_id'],
    userId1: !exists(json, 'user_id_1') ? undefined : json['user_id_1'],
    userId2: !exists(json, 'user_id_2') ? undefined : json['user_id_2'],
  }
}

export function AppointmentSerializerReadToJSON(
  value?: AppointmentSerializerRead,
): any {
  if (value === undefined) {
    return undefined
  }
  return {
    appointment_id: value.appointmentId,
    tag_id: value.tagId,
    date_start: value.dateStart,
    date_end: value.dateEnd,
    note: value.note,
    reminder: value.reminder,
    property_id: value.propertyId,
    user_id_1: value.userId1,
    user_id_2: value.userId2,
  }
}
