// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime'
/**
 *
 * @export
 * @interface ArticleSerializerPost
 */
export interface ArticleSerializerPost {
  /**
   *
   * @type {string}
   * @memberof ArticleSerializerPost
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof ArticleSerializerPost
   */
  content?: string
  /**
   *
   * @type {number}
   * @memberof ArticleSerializerPost
   */
  tag_id?: number
  /**
   *
   * @type {number}
   * @memberof ArticleSerializerPost
   */
  user_id?: number
}

export function ArticleSerializerPostFromJSON(
  json: any,
): ArticleSerializerPost {
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    content: !exists(json, 'content') ? undefined : json['content'],
    tag_id: !exists(json, 'tag_id') ? undefined : json['tag_id'],
    user_id: !exists(json, 'user_id') ? undefined : json['user_id'],
  }
}

export function ArticleSerializerPostToJSON(
  value?: ArticleSerializerPost,
): any {
  if (value === undefined) {
    return undefined
  }
  return {
    name: value.name,
    content: value.content,
    tag_id: value.tag_id,
    user_id: value.user_id,
  }
}
