// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface FeeSerializerRead
 */
export interface FeeSerializerRead {
  /**
   *
   * @type {number}
   * @memberof FeeSerializerRead
   */
  feeId?: number
  /**
   *
   * @type {string}
   * @memberof FeeSerializerRead
   */
  rentFee?: string
  /**
   *
   * @type {string}
   * @memberof FeeSerializerRead
   */
  sellFee?: string
  /**
   *
   * @type {string}
   * @memberof FeeSerializerRead
   */
  squareFee?: string
  /**
   *
   * @type {string}
   * @memberof FeeSerializerRead
   */
  gestionFee?: string
}

export function FeeSerializerReadFromJSON(json: any): FeeSerializerRead {
  return {
    feeId: !exists(json, 'fee_id') ? undefined : json['fee_id'],
    rentFee: !exists(json, 'rent_fee') ? undefined : json['rent_fee'],
    sellFee: !exists(json, 'sell_fee') ? undefined : json['sell_fee'],
    squareFee: !exists(json, 'square_fee') ? undefined : json['square_fee'],
    gestionFee: !exists(json, 'gestion_fee') ? undefined : json['gestion_fee'],
  }
}

export function FeeSerializerReadToJSON(value?: FeeSerializerRead): any {
  if (value === undefined) {
    return undefined
  }
  return {
    fee_id: value.feeId,
    rent_fee: value.rentFee,
    sell_fee: value.sellFee,
    square_fee: value.squareFee,
    gestion_fee: value.gestionFee,
  }
}
