// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GenericError
 */
export interface GenericError {
  [key: string]: any | any
  /**
   * The error name
   * @type {string}
   * @memberof GenericError
   */
  name: string
  /**
   * An error message
   * @type {string}
   * @memberof GenericError
   */
  message: string
}

export function GenericErrorFromJSON(json: any): GenericError {
  return {
    ...json,
    name: json['name'],
    message: json['message'],
  }
}

export function GenericErrorToJSON(value?: GenericError): any {
  if (value === undefined) {
    return undefined
  }
  return {
    ...value,
    name: value.name,
    message: value.message,
  }
}
