// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime'
/**
 *
 * @export
 * @interface MailsSubscribeNewsletterRequest
 */
export interface MailsSubscribeNewsletterRequest {
  /**
   *
   * @type {string}
   * @memberof MailsSubscribeNewsletterRequest
   */
  mail?: string
}

export function MailsSubscribeNewsletterRequestFromJSON(
  json: any,
): MailsSubscribeNewsletterRequest {
  return {
    mail: !exists(json, 'mail') ? undefined : json['mail'],
  }
}

export function MailsSubscribeNewsletterRequestToJSON(
  value?: MailsSubscribeNewsletterRequest,
): any {
  if (value === undefined) {
    return undefined
  }
  return {
    mail: value.mail,
  }
}
