// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime'
/**
 *
 * @export
 * @interface MessageSerializerPut
 */
export interface MessageSerializerPut {
  /**
   *
   * @type {string}
   * @memberof MessageSerializerPut
   */
  content?: string
}

export function MessageSerializerPutFromJSON(json: any): MessageSerializerPut {
  return {
    content: !exists(json, 'content') ? undefined : json['content'],
  }
}

export function MessageSerializerPutToJSON(value?: MessageSerializerPut): any {
  if (value === undefined) {
    return undefined
  }
  return {
    content: value.content,
  }
}
