// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime'
/**
 *
 * @export
 * @interface PermissionSerializerRead
 */
export interface PermissionSerializerRead {
  /**
   *
   * @type {number}
   * @memberof PermissionSerializerRead
   */
  permission_id?: number
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  properties?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  addresses?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  agencies?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  appointments?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  articles?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  attachments?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  bookmarks?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  countries?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  fees?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  messages?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  roles?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  sectors?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  statuses?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  tags?: string
  /**
   *
   * @type {string}
   * @memberof PermissionSerializerRead
   */
  users?: string
}

export function PermissionSerializerReadFromJSON(
  json: any,
): PermissionSerializerRead {
  return {
    permission_id: !exists(json, 'permission_id')
      ? undefined
      : json['permission_id'],
    properties: !exists(json, 'properties') ? undefined : json['properties'],
    addresses: !exists(json, 'addresses') ? undefined : json['addresses'],
    agencies: !exists(json, 'agencies') ? undefined : json['agencies'],
    appointments: !exists(json, 'appointments')
      ? undefined
      : json['appointments'],
    articles: !exists(json, 'articles') ? undefined : json['articles'],
    attachments: !exists(json, 'attachments') ? undefined : json['attachments'],
    bookmarks: !exists(json, 'bookmarks') ? undefined : json['bookmarks'],
    countries: !exists(json, 'countries') ? undefined : json['countries'],
    fees: !exists(json, 'fees') ? undefined : json['fees'],
    messages: !exists(json, 'messages') ? undefined : json['messages'],
    roles: !exists(json, 'roles') ? undefined : json['roles'],
    sectors: !exists(json, 'sectors') ? undefined : json['sectors'],
    statuses: !exists(json, 'statuses') ? undefined : json['statuses'],
    tags: !exists(json, 'tags') ? undefined : json['tags'],
    users: !exists(json, 'users') ? undefined : json['users'],
  }
}

export function PermissionSerializerReadToJSON(
  value?: PermissionSerializerRead,
): any {
  if (value === undefined) {
    return undefined
  }
  return {
    permission_id: value.permission_id,
    properties: value.properties,
    addresses: value.addresses,
    agencies: value.agencies,
    appointments: value.appointments,
    articles: value.articles,
    attachments: value.attachments,
    bookmarks: value.bookmarks,
    countries: value.countries,
    fees: value.fees,
    messages: value.messages,
    roles: value.roles,
    sectors: value.sectors,
    statuses: value.statuses,
    tags: value.tags,
    users: value.users,
  }
}
