// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleSerializerPut
 */
export interface RoleSerializerPut  {
    /**
     * 
     * @type {string}
     * @memberof RoleSerializerPut
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof RoleSerializerPut
     */
    permission_id?: number;
}

export function RoleSerializerPutFromJSON(json: any): RoleSerializerPut {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'permission_id': !exists(json, 'permission_id') ? undefined : json['permission_id'],
    };
}

export function RoleSerializerPutToJSON(value?: RoleSerializerPut): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'permission_id': value.permission_id,
    };
}


