// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime'
/**
 *
 * @export
 * @interface RoleSerializerPost
 */
export interface RoleSerializerPost {
  /**
   *
   * @type {string}
   * @memberof RoleSerializerPost
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof RoleSerializerPost
   */
  permission_id?: number
}

export function RoleSerializerPostFromJSON(json: any): RoleSerializerPost {
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    permission_id: !exists(json, 'permission_id')
      ? undefined
      : json['permission_id'],
  }
}

export function RoleSerializerPostToJSON(value?: RoleSerializerPost): any {
  if (value === undefined) {
    return undefined
  }
  return {
    name: value.name,
    permission_id: value.permission_id,
  }
}
