// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime'
/**
 *
 * @export
 * @interface StatusSerializerPost
 */
export interface StatusSerializerPost {
  /**
   *
   * @type {string}
   * @memberof StatusSerializerPost
   */
  name?: string
}

export function StatusSerializerPostFromJSON(json: any): StatusSerializerPost {
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
  }
}

export function StatusSerializerPostToJSON(value?: StatusSerializerPost): any {
  if (value === undefined) {
    return undefined
  }
  return {
    name: value.name,
  }
}
