// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusSerializerRead
 */
export interface StatusSerializerRead  {
    /**
     * 
     * @type {number}
     * @memberof StatusSerializerRead
     */
    status_id?: number;
    /**
     * 
     * @type {string}
     * @memberof StatusSerializerRead
     */
    name?: string;
}

export function StatusSerializerReadFromJSON(json: any): StatusSerializerRead {
    return {
        'status_id': !exists(json, 'status_id') ? undefined : json['status_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function StatusSerializerReadToJSON(value?: StatusSerializerRead): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'status_id': value.status_id,
        'name': value.name,
    };
}


