// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UserSerializerRead
 */
export interface UserSerializerRead {
  /**
   *
   * @type {number}
   * @memberof UserSerializerRead
   */
  userId?: number
  /**
   *
   * @type {string}
   * @memberof UserSerializerRead
   */
  firstname?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerRead
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerRead
   */
  phone?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerRead
   */
  mail?: string
  /**
   *
   * @type {boolean}
   * @memberof UserSerializerRead
   */
  newsletter?: boolean
  /**
   *
   * @type {string}
   * @memberof UserSerializerRead
   */
  validatedAt?: string
  /**
   *
   * @type {number}
   * @memberof UserSerializerRead
   */
  addressId?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerRead
   */
  countryId?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerRead
   */
  roleId?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerRead
   */
  agencyId?: number
}

export function UserSerializerReadFromJSON(json: any): UserSerializerRead {
  return {
    userId: !exists(json, 'user_id') ? undefined : json['user_id'],
    firstname: !exists(json, 'firstname') ? undefined : json['firstname'],
    name: !exists(json, 'name') ? undefined : json['name'],
    phone: !exists(json, 'phone') ? undefined : json['phone'],
    mail: !exists(json, 'mail') ? undefined : json['mail'],
    newsletter: !exists(json, 'newsletter') ? undefined : json['newsletter'],
    validatedAt: !exists(json, 'validated_at')
      ? undefined
      : json['validated_at'],
    addressId: !exists(json, 'address_id') ? undefined : json['address_id'],
    countryId: !exists(json, 'country_id') ? undefined : json['country_id'],
    roleId: !exists(json, 'role_id') ? undefined : json['role_id'],
    agencyId: !exists(json, 'agency_id') ? undefined : json['agency_id'],
  }
}

export function UserSerializerReadToJSON(value?: UserSerializerRead): any {
  if (value === undefined) {
    return undefined
  }
  return {
    user_id: value.userId,
    firstname: value.firstname,
    name: value.name,
    phone: value.phone,
    mail: value.mail,
    newsletter: value.newsletter,
    validated_at: value.validatedAt,
    address_id: value.addressId,
    country_id: value.countryId,
    role_id: value.roleId,
    agency_id: value.agencyId,
  }
}
