// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime'
/**
 *
 * @export
 * @interface UserSerializerPut
 */
export interface UserSerializerPut {
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  phone?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  mail?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  password?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  new_password?: string
  /**
   *
   * @type {boolean}
   * @memberof UserSerializerPut
   */
  newsletter?: boolean
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  validated_at?: string
  /**
   *
   * @type {number}
   * @memberof UserSerializerPut
   */
  address_id?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerPut
   */
  country_id?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerPut
   */
  role_id?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerPut
   */
  agency_id?: number
}

export function UserSerializerPutFromJSON(json: any): UserSerializerPut {
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    phone: !exists(json, 'phone') ? undefined : json['phone'],
    mail: !exists(json, 'mail') ? undefined : json['mail'],
    password: !exists(json, 'password') ? undefined : json['password'],
    new_password: !exists(json, 'newPassword')
      ? undefined
      : json['newPassword'],
    newsletter: !exists(json, 'newsletter') ? undefined : json['newsletter'],
    validated_at: !exists(json, 'validated_at')
      ? undefined
      : json['validated_at'],
    address_id: !exists(json, 'address_id') ? undefined : json['address_id'],
    country_id: !exists(json, 'country_id') ? undefined : json['country_id'],
    role_id: !exists(json, 'role_id') ? undefined : json['role_id'],
    agency_id: !exists(json, 'agency_id') ? undefined : json['agency_id'],
  }
}

export function UserSerializerPutToJSON(value?: UserSerializerPut): any {
  if (value === undefined) {
    return undefined
  }
  return {
    name: value.name,
    phone: value.phone,
    mail: value.mail,
    password: value.password,
    newPassword: value.new_password,
    newsletter: value.newsletter,
    validated_at: value.validated_at,
    address_id: value.address_id,
    country_id: value.country_id,
    role_id: value.role_id,
    agency_id: value.agency_id,
  }
}
