// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthentificationsLoginRequest
 */
export interface AuthentificationsLoginRequest  {
    /**
     * 
     * @type {string}
     * @memberof AuthentificationsLoginRequest
     */
    mail?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthentificationsLoginRequest
     */
    password?: string;
}

export function AuthentificationsLoginRequestFromJSON(json: any): AuthentificationsLoginRequest {
    return {
        'mail': !exists(json, 'mail') ? undefined : json['mail'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function AuthentificationsLoginRequestToJSON(value?: AuthentificationsLoginRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'mail': value.mail,
        'password': value.password,
    };
}


