// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeeSerializerPut
 */
export interface FeeSerializerPut  {
    /**
     * 
     * @type {string}
     * @memberof FeeSerializerPut
     */
    rentFee?: string;
    /**
     * 
     * @type {string}
     * @memberof FeeSerializerPut
     */
    sellFee?: string;
    /**
     * 
     * @type {string}
     * @memberof FeeSerializerPut
     */
    squareFee?: string;
    /**
     * 
     * @type {string}
     * @memberof FeeSerializerPut
     */
    gestionFee?: string;
}

export function FeeSerializerPutFromJSON(json: any): FeeSerializerPut {
    return {
        'rentFee': !exists(json, 'rent_fee') ? undefined : json['rent_fee'],
        'sellFee': !exists(json, 'sell_fee') ? undefined : json['sell_fee'],
        'squareFee': !exists(json, 'square_fee') ? undefined : json['square_fee'],
        'gestionFee': !exists(json, 'gestion_fee') ? undefined : json['gestion_fee'],
    };
}

export function FeeSerializerPutToJSON(value?: FeeSerializerPut): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'rent_fee': value.rentFee,
        'sell_fee': value.sellFee,
        'square_fee': value.squareFee,
        'gestion_fee': value.gestionFee,
    };
}


