// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SectorSerializerRead
 */
export interface SectorSerializerRead  {
    /**
     * 
     * @type {number}
     * @memberof SectorSerializerRead
     */
    sectorId?: number;
    /**
     * 
     * @type {string}
     * @memberof SectorSerializerRead
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SectorSerializerRead
     */
    polygon?: string;
    /**
     * 
     * @type {number}
     * @memberof SectorSerializerRead
     */
    agencyId?: number;
}

export function SectorSerializerReadFromJSON(json: any): SectorSerializerRead {
    return {
        'sectorId': !exists(json, 'sector_id') ? undefined : json['sector_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'polygon': !exists(json, 'polygon') ? undefined : json['polygon'],
        'agencyId': !exists(json, 'agency_id') ? undefined : json['agency_id'],
    };
}

export function SectorSerializerReadToJSON(value?: SectorSerializerRead): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'sector_id': value.sectorId,
        'name': value.name,
        'polygon': value.polygon,
        'agency_id': value.agencyId,
    };
}


