// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UserSerializerPut
 */
export interface UserSerializerPut {
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  phone?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  mail?: string
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  password?: string
  /**
   *
   * @type {boolean}
   * @memberof UserSerializerPut
   */
  newsletter?: boolean
  /**
   *
   * @type {string}
   * @memberof UserSerializerPut
   */
  validatedAt?: string
  /**
   *
   * @type {number}
   * @memberof UserSerializerPut
   */
  addressId?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerPut
   */
  countryId?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerPut
   */
  roleId?: number
  /**
   *
   * @type {number}
   * @memberof UserSerializerPut
   */
  agencyId?: number
}

export function UserSerializerPutFromJSON(json: any): UserSerializerPut {
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    phone: !exists(json, 'phone') ? undefined : json['phone'],
    mail: !exists(json, 'mail') ? undefined : json['mail'],
    password: !exists(json, 'password') ? undefined : json['password'],
    newsletter: !exists(json, 'newsletter') ? undefined : json['newsletter'],
    validatedAt: !exists(json, 'validated_at')
      ? undefined
      : json['validated_at'],
    addressId: !exists(json, 'address_id') ? undefined : json['address_id'],
    countryId: !exists(json, 'country_id') ? undefined : json['country_id'],
    roleId: !exists(json, 'role_id') ? undefined : json['role_id'],
    agencyId: !exists(json, 'agency_id') ? undefined : json['agency_id'],
  }
}

export function UserSerializerPutToJSON(value?: UserSerializerPut): any {
  if (value === undefined) {
    return undefined
  }
  return {
    name: value.name,
    phone: value.phone,
    mail: value.mail,
    password: value.password,
    newsletter: value.newsletter,
    validated_at: value.validatedAt,
    address_id: value.addressId,
    country_id: value.countryId,
    role_id: value.roleId,
    agency_id: value.agencyId,
  }
}
